### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by kschwerdtfeger** [flinthillsdesign/cvifs-issues#48]
Is there any way I can get a copy of our master product database and pricing databases?

**Comment by davegaeddert** [comment]
Hey @kschwerdtfeger, what kind of export are you looking for? I can easily give you a dump of the Postgres database... A CSV will get a little more complicated due to all of the relationships throughout the database, so if that's what you need than it would be good to know specifics of what you need (and maybe what you plan to do with it).

**Comment by kschwerdtfeger** [comment]
Postgres is fine!

**Comment by davegaeddert** [comment]
This should be it: https://www.dropbox.com/s/vllvnrev2sj5gi0/cvi_db.sql.gz?dl=0

**Comment by davegaeddert** [comment]
Sorry, just remembered that this repo is technically "public" so I don't want to put that link out there. I'll email it to you.
